season: 1
lang: en
difficulty: hard
chapter_length: 25
border_radius: 1500
closable_border: true
final_radius: 150
border_closing_episode: 8


# If this feature is enabled all player's will be randomly disguised with other participant's skin and names periodically
rotate_skins:
  enabled: true
  period: 2 # The period in episodes when a skin rotations cycle will be executed

# If this feature is enabled, the plugin will give a shulkerbox to all alive players on the specified episode.
# If the player has got no space in their inventory, a shulkerbox item will be dropped at their location.
auto_shulker:
  enabled: true
  episode: 8

# If this section is enabled ghast drops will be replaced by the following drops.
# If the specified item type does not exist, ghasts will drop default ghast tears.
custom_ghast_drops:
  enabled: true
  item: gold_ingot # Minecraft item id.
  amount: 1 # Amount of the item


# Hyper golden apple settings
hga:
  containers: 2 # 1 container = 2 hp (1 heart)

# Probability of a drowned dropping a trident
trident_drop: 0.5 # Probability from 0 (0%) to 1 (100%)